import React from 'react';

// Translations are now nested by page to prevent key conflicts.
const translations = {
  en: {
    // Keys used across multiple components
    common: {
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      area: "Area",
      irrigation: "Irrigation",
      confidence: "Confidence",
      severity: "Severity",
      analyzing: "Analyzing...",
    },
    // MyFarms.jsx translations
    myFarms: {
      pageTitle: "My Farms",
      pageSubtitle: "Manage and monitor all your registered farms.",
      addNewFarm: "Add New Farm",
      totalFarms: "Total Farms",
      totalArea: "Total Area",
      activeFarms: "Active Farms",
      cropTypes: "Crop Types",
      currentCrop: "Current Crop",
      soilType: "Soil Type",
      planted: "Planted",
      harvest: "Harvest",
      noFarmsTitle: "No farms registered",
      noFarmsSubtitle: "Get started by adding your first farm.",
      addFirstFarm: "Add Your First Farm",
      confirmDeletionTitle: "Confirm Deletion",
      confirmDeletionText: (farmName) => `Are you sure you want to delete "${farmName}"? This action cannot be undone.`,
    },
    // Dashboard.jsx translations
    dashboard: {
        title: "AgroCare AI",
        tagline: "Smart Farming Assistant",
        todaysDate: "Today's Date",
        fillDetails: "Fill Your Farm Details",
        crop: "Crop",
        cropPlaceholder: "e.g., Rice, Wheat",
        season: "Season",
        selectSeason: "Select Season",
        rabi: "Rabi",
        kharif: "Kharif",
        wholeYear: "Whole Year",
        summer: "Summer",
        autumn: "Autumn",
        winter: "Winter",
        state: "State",
        statePlaceholder: "e.g., Gujarat",
        area: "Area (in hectare)",
        areaPlaceholder: "e.g., 2.5",
        rainfall: "Annual Rainfall (in mm)",
        rainfallPlaceholder: "e.g., 1200",
        fertilizer: "Fertilizer (in kg/hectare)",
        fertilizerPlaceholder: "e.g., 50",
        pesticide: "Pesticide (in kg/hectare)",
        pesticidePlaceholder: "e.g., 2",
        estimateYield: "Estimate Yield",
        calculating: "Calculating...",
        suggestions: "Suggestions",
        irrigationText: "Next watering in 2 days",
        fertilization: "Fertilization",
        fertilizationText: "Apply NPK next week",
        pestControl: "Pest Control",
        pestControlText: "Monitor for aphids",
        estimatedYield: "Your Estimated Yield",
        nutsPerHectare: "nuts per hectare",
        tonsPerHectare: "tons per hectare",
        targetComparison: "Target Comparison",
        targetAchieved: "Target Achieved",
        targetRemaining: "Target Remaining",
        ofTarget: "of target",
        fertilizerImpact: "Fertilizer Impact",
        impactOnYield: "Impact on Yield",
        low: "Low",
        medium: "Medium",
        high: "High",
        historicalYieldRainfall: "Historical Yield & Rainfall",
        yieldLabel: "Yield (tons/hectare)",
        rainfallLabel: "Rainfall (mm)",
        error: "Error getting estimate. Please try again.",
    },
    // CropRecommender.jsx translations
    cropRecommender: {
        pageTitle: "Find the Best Crop for Your Land",
        pageSubtitle: "Select one of your farms to get started, or enter your soil details manually to receive AI-powered crop recommendations.",
        soilAnalysisInput: "Soil Analysis Input",
        selectFarm: "Select a Farm (Optional)",
        selectFarmPlaceholder: "Choose a farm to auto-fill data...",
        farmDataLoaded: "✓ Farm data loaded automatically. You can modify the values below if needed.",
        nitrogen: "Nitrogen (N) Level",
        phosphorus: "Phosphorus (P) Level",
        potassium: "Potassium (K) Level",
        ph: "Soil pH Level",
        unit: "(mg/kg)",
        phUnit: "(0-14 scale)",
        placeholder_e_g: "e.g.,",
        recommendCrop: "Recommend Crop",
        analyzing: "Analyzing Soil...",
        recommendedCropTitle: "Recommended Crop",
        suitability: "Suitability",
        excellentMatch: "Excellent Match",
        veryGoodMatch: "Very Good Match",
        goodMatch: "Good Match",
        fairMatch: "Fair Match",
        nextSteps: "Next Steps",
        nextStepsText: "Consider consulting with local agricultural experts and check market conditions before planting. You may also want to test a small area first to validate these recommendations.",
        fillAllFields: "Please fill in all soil parameter fields",
    },
    // PestIdentifier.jsx translations
    pestIdentifier: {
        pageTitle: "Identify Pests and Diseases",
        pageSubtitle: "Upload a clear photo of the affected plant leaf or pest to get an instant AI-powered analysis and treatment recommendations.",
        uploadTitle: "Upload Plant Image",
        dropPrompt: "Drop image here",
        uploadPrompt: "Drag and drop your image here, or click to browse files",
        clickToUpload: "Click to Upload Photo",
        fileSupport: "Supports JPG, PNG, WebP files up to 10MB",
        imagePreview: "Image Preview",
        analyze: "Analyze Image",
        analyzing: "Analyzing Image...",
        analysisResult: "Analysis Result",
        symptoms: "Common Symptoms",
        recommendedActions: "Recommended Actions",
        organicSolutions: "Organic Solutions",
        preventionTips: "Prevention Tips",
        getTreatmentGuide: "Get Detailed Treatment Guide",
        findSuppliers: "Find Local Suppliers",
        analyzeAnother: "Analyze Another Image",
        alert_selectImage: "Please select an image first",
        alert_invalidFile: "Please select a valid image file (JPG, PNG, etc.)",
    }
  },
  hi: {
    common: {
        cancel: "रद्द करें",
        delete: "हटाएं",
        edit: "संपादित करें",
        area: "क्षेत्रफल",
        irrigation: "सिंचाई",
        confidence: "आत्मविश्वास",
        severity: "गंभीरता",
        analyzing: "विश्लेषण हो रहा है...",
    },
    myFarms: {
        pageTitle: "मेरे खेत",
        pageSubtitle: "अपने सभी पंजीकृत खेतों का प्रबंधन और निगरानी करें।",
        addNewFarm: "नया खेत जोड़ें",
        totalFarms: "कुल खेत",
        totalArea: "कुल क्षेत्रफल",
        activeFarms: "सक्रिय खेत",
        cropTypes: "फसल के प्रकार",
        currentCrop: "वर्तमान फसल",
        soilType: "मिट्टी का प्रकार",
        planted: "रोपण",
        harvest: "कटाई",
        noFarmsTitle: "कोई खेत पंजीकृत नहीं है",
        noFarmsSubtitle: "अपना पहला खेत जोड़कर शुरुआत करें।",
        addFirstFarm: "अपना पहला खेत जोड़ें",
        confirmDeletionTitle: "हटाने की पुष्टि करें",
        confirmDeletionText: (farmName) => `क्या आप वाकई "${farmName}" को हटाना चाहते हैं? यह कार्रवाई पूर्ववत नहीं की जा सकती।`,
    },
    dashboard: {
        title: "एग्रोकेयर AI",
        tagline: "किसान सहायक",
        todaysDate: "आज की तारीख",
        fillDetails: "अपने खेत की जानकारी भरें",
        crop: "फसल",
        cropPlaceholder: "जैसे: धान, गेहूँ",
        season: "मौसम",
        selectSeason: "मौसम चुनें",
        rabi: "रबी",
        kharif: "खरीफ",
        wholeYear: "पूरे साल",
        summer: "गर्मी",
        autumn: "पतझड़",
        winter: "सर्दी",
        state: "राज्य",
        statePlaceholder: "जैसे, गुजरात",
        area: "ज़मीन (हेक्टेयर में)",
        areaPlaceholder: "जैसे: 2.5",
        rainfall: "सालाना बारिश (मिमी में)",
        rainfallPlaceholder: "जैसे: 1200",
        fertilizer: "खाद (किलो/हेक्टेयर)",
        fertilizerPlaceholder: "जैसे: 50",
        pesticide: "दवाई (किलो/हेक्टेयर)",
        pesticidePlaceholder: "जैसे: 2",
        estimateYield: "पैदावार का अनुमान लगाएं",
        calculating: "गिनती हो रही है...",
        suggestions: "सुझाव",
        irrigationText: "अगली सिंचाई 2 दिन में करें",
        fertilization: "खाद कब डालें",
        fertilizationText: "अगले हफ्ते NPK खाद डालें",
        pestControl: "कीड़ों से बचाव",
        pestControlText: "माहू (aphids) के लिए फसल देखें",
        estimatedYield: "आपकी अनुमानित पैदावार",
        nutsPerHectare: "नट्स प्रति हेक्टेयर ",
        tonsPerHectare: "टन प्रति हेक्टेयर",
        targetComparison: "लक्ष्य की तुलना",
        targetAchieved: "लक्ष्य पूरा हुआ",
        targetRemaining: "लक्ष्य बाकी",
        ofTarget: "लक्ष्य का",
        fertilizerImpact: "खाद का असर",
        impactOnYield: "पैदावार पर असर",
        low: "कम खाद",
        medium: "ठीक खाद",
        high: "ज़्यादा खाद",
        historicalYieldRainfall: "पिछले सालों की पैदावार और बारिश",
        yieldLabel: "पैदावार (टन/हेक्टेयर)",
        rainfallLabel: "बारिश (मिमी)",
        error: "अनुमान लगाने में कुछ गलती हुई। कृपया फिर से प्रयास करें।",
    },
    cropRecommender: {
        pageTitle: "अपनी ज़मीन के लिए सबसे अच्छी फ़सल चुनें",
        pageSubtitle: "शुरू करने के लिए अपने किसी एक खेत का चयन करें, या AI-संचालित फसल सिफारिशें प्राप्त करने के लिए अपनी मिट्टी का विवरण मैन्युअल रूप से दर्ज करें।",
        soilAnalysisInput: "मिट्टी विश्लेषण इनपुट",
        selectFarm: "एक खेत चुनें (वैकल्पिक)",
        selectFarmPlaceholder: "डेटा ऑटो-फिल करने के लिए एक खेत चुनें...",
        farmDataLoaded: "✓ खेत का डेटा स्वचालित रूप से लोड हो गया है। यदि आवश्यक हो तो आप नीचे दिए गए मानों को संशोधित कर सकते हैं।",
        nitrogen: "नाइट्रोजन (N) स्तर",
        phosphorus: "फास्फोरस (P) स्तर",
        potassium: "पोटेशियम (K) स्तर",
        ph: "मिट्टी का पीएच स्तर",
        unit: "(मिग्रा/किग्रा)",
        phUnit: "(0-14 पैमाना)",
        placeholder_e_g: "जैसे,",
        recommendCrop: "फसल की सिफारिश करें",
        analyzing: "मिट्टी का विश्लेषण हो रहा है...",
        recommendedCropTitle: "अनुशंसित फसल",
        suitability: "उपयुक्तता",
        excellentMatch: "उत्कृष्ट मेल",
        veryGoodMatch: "बहुत अच्छा मेल",
        goodMatch: "अच्छा मेल",
        fairMatch: "ठीक मेल",
        nextSteps: "अगले कदम",
        nextStepsText: "रोपण से पहले स्थानीय कृषि विशेषज्ञों से परामर्श करने और बाजार की स्थितियों की जांच करने पर विचार करें। इन सिफारिशों को मान्य करने के लिए आप पहले एक छोटे से क्षेत्र का परीक्षण भी कर सकते हैं।",
        fillAllFields: "कृपया सभी मिट्टी पैरामीटर फ़ील्ड भरें",
    },
    pestIdentifier: {
        pageTitle: "कीटों और रोगों की पहचान करें",
        pageSubtitle: "तत्काल AI-संचालित विश्लेषण और उपचार सिफारिशें प्राप्त करने के लिए प्रभावित पौधे के पत्ते या कीट की एक स्पष्ट तस्वीर अपलोड करें।",
        uploadTitle: "पौधे की तस्वीर अपलोड करें",
        dropPrompt: "तस्वीर यहाँ छोड़ें",
        uploadPrompt: "अपनी तस्वीर यहाँ खींचें और छोड़ें, या फाइल ब्राउज़ करने के लिए क्लिक करें",
        clickToUpload: "तस्वीर अपलोड करने के लिए क्लिक करें",
        fileSupport: "10MB तक की JPG, PNG, WebP फ़ाइलों का समर्थन करता है",
        imagePreview: "छवि पूर्वावलोकन",
        analyze: "छवि का विश्लेषण करें",
        analyzing: "छवि का विश्लेषण हो रहा है...",
        analysisResult: "विश्लेषण परिणाम",
        symptoms: "सामान्य लक्षण",
        recommendedActions: "अनुशंसित कार्रवाइयां",
        organicSolutions: "जैविक समाधान",
        preventionTips: "रोकथाम युक्तियाँ",
        getTreatmentGuide: "विस्तृत उपचार गाइड प्राप्त करें",
        findSuppliers: "स्थानीय आपूर्तिकर्ता खोजें",
        analyzeAnother: "दूसरी छवि का विश्लेषण करें",
        alert_selectImage: "कृपया पहले एक छवि चुनें",
        alert_invalidFile: "कृपया एक वैध छवि फ़ाइल (JPG, PNG, आदि) चुनें।",
    }
  },
  or: {
    common: {
        cancel: "ବାତିଲ କରନ୍ତୁ",
        delete: "ଡିଲିଟ୍ କରନ୍ତୁ",
        edit: "ସମ୍ପାଦନ କରନ୍ତୁ",
        area: "କ୍ଷେତ୍ର",
        irrigation: "ଜଳସେଚନ",
        confidence: "ଆତ୍ମବିଶ୍ୱାସ",
        severity: "ଗମ୍ଭୀରତା",
        analyzing: "ବିଶ୍ଳେଷଣ କରୁଛି...",
    },
    myFarms: {
        pageTitle: "ମୋର ଫାର୍ମ",
        pageSubtitle: "ଆପଣଙ୍କର ସମସ୍ତ ପଞ୍ଜୀକୃତ ଫାର୍ମ ପରିଚାଳନା ଏବଂ ମନିଟର କରନ୍ତୁ |",
        addNewFarm: "ନୂଆ ଫାର୍ମ ଯୋଡନ୍ତୁ",
        totalFarms: "ମୋଟ ଫାର୍ମ",
        totalArea: "ମୋଟ କ୍ଷେତ୍ର",
        activeFarms: "ସକ୍ରିୟ ଫାର୍ମ",
        cropTypes: "ଫସଲ ପ୍ରକାର",
        currentCrop: "ବର୍ତ୍ତମାନର ଫସଲ",
        soilType: "ମାଟିର ପ୍ରକାର",
        planted: "ରୋପଣ କରାଯାଇଛି",
        harvest: "ଅମଳ",
        noFarmsTitle: "କୌଣସି ଫାର୍ମ ପଞ୍ଜୀକୃତ ହୋଇନାହିଁ",
        noFarmsSubtitle: "ଆପଣଙ୍କର ପ୍ରଥମ ଫାର୍ମ ଯୋଡି ଆରମ୍ଭ କରନ୍ତୁ |",
        addFirstFarm: "ଆପଣଙ୍କର ପ୍ରଥମ ଫାର୍ମ ଯୋଡନ୍ତୁ",
        confirmDeletionTitle: "ବିଲୋପ ନିଶ୍ଚିତ କରନ୍ତୁ",
        confirmDeletionText: (farmName) => `ଆପଣ ନିଶ୍ଚିତ କି "${farmName}" କୁ ବିଲୋପ କରିବାକୁ ଚାହୁଁଛନ୍ତି? ଏହି କାର୍ଯ୍ୟକୁ ପୂର୍ବବତ୍ କରାଯାଇପାରିବ ନାହିଁ।`,
    },
    dashboard: {
        title: "ଏଗ୍ରୋକେୟାର AI",
        tagline: "କୃଷକ ସହାୟକ",
        todaysDate: "ଆଜିର ତାରିଖ",
        fillDetails: "ଆପଣଙ୍କ ଫାର୍ମ ବିବରଣୀ ପୁରଣ କରନ୍ତୁ",
        crop: "ଫସଲ",
        cropPlaceholder: "ଉଦାହରଣ: ଧାନ, ଗହମ",
        season: "ଋତୁ",
        selectSeason: "ଋତୁ ବାଛନ୍ତୁ",
        rabi: "ରବି",
        kharif: "ଖରିଫ",
        wholeYear: "ବର୍ଷ ସାରା",
        summer: "ଗ୍ରୀଷ୍ମ",
        autumn: "ଶରତ",
        winter: "ଶୀତ",
        state: "ରାଜ୍ୟ",
        statePlaceholder: "ଯଥା, ଗୁଜୁରାଟ |",
        area: "ଜମି (ହେକ୍ଟରରେ)",
        areaPlaceholder: "ଉଦାହରଣ: 2.5",
        rainfall: "ବାର୍ଷିକ ବର୍ଷା (ମିମିରେ)",
        rainfallPlaceholder: "ଉଦାହରଣ: 1200",
        fertilizer: "ସାର (କିଲୋ/ହେକ୍ଟର)",
        fertilizerPlaceholder: "ଉଦାହରଣ: 50",
        pesticide: "କୀଟନାଶକ (କିଲୋ/ହେକ୍ଟର)",
        pesticidePlaceholder: "ଉଦାହରଣ: 2",
        estimateYield: "ଉତ୍ପାଦନ ଅନୁମାନ କରନ୍ତୁ",
        calculating: "ଗଣନା କରାଯାଉଛି...",
        suggestions: "ପରାମର୍ଶ",
        irrigationText: "ପରବର୍ତ୍ତୀ ଜଳସେଚନ 2 ଦିନରେ",
        fertilization: "ସାର ପ୍ରୟୋଗ",
        fertilizationText: "ଆସନ୍ତା ସପ୍ତାହରେ NPK ପ୍ରୟୋଗ କରନ୍ତୁ",
        pestControl: "କୀଟ ନିୟନ୍ତ୍ରଣ",
        pestControlText: "ଏଫିଡ୍ ପାଇଁ ନଜର ରଖନ୍ତୁ",
        estimatedYield: "ଆପଣଙ୍କର ଅନୁମାନିତ ଉତ୍ପାଦନ",
        nutsPerHectare: "ବାଦାମ |/ହେକ୍ଟର",
        tonsPerHectare: "ଟନ୍/ହେକ୍ଟର",
        targetComparison: "ଲକ୍ଷ୍ୟ ତୁଳନା",
        targetAchieved: "ଲକ୍ଷ୍ୟ ହାସଲ ହେଲା",
        targetRemaining: "ଲକ୍ଷ୍ୟ ବାକି ଅଛି",
        ofTarget: "ଲକ୍ଷ୍ୟର",
        fertilizerImpact: "ସାରର ପ୍ରଭାବ",
        impactOnYield: "ଉତ୍ପାଦନ ଉପରେ ପ୍ରଭାବ",
        low: "କମ୍",
        medium: "ମଧ୍ୟମ",
        high: "ଅଧିକ",
        historicalYieldRainfall: "ଅତୀତର ଉତ୍ପାଦନ ଏବଂ ବର୍ଷା",
        yieldLabel: "ଉତ୍ପାଦନ (ଟନ୍/ହେକ୍ଟର)",
        rainfallLabel: "ବର୍ଷା (ମିମି)",
        error: "ଅନୁମାନ କରିବାରେ ତ୍ରୁଟି। ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।",
    },
    cropRecommender: {
        pageTitle: "ଆପଣଙ୍କ ଜମି ପାଇଁ ସର୍ବୋତ୍ତମ ଫସଲ ଖୋଜନ୍ତୁ",
        pageSubtitle: "ଆରମ୍ଭ କରିବାକୁ ଆପଣଙ୍କର ଏକ ଫାର୍ମ ବାଛନ୍ତୁ, କିମ୍ବା AI- ଚାଳିତ ଫସଲ ସୁପାରିଶ ପାଇବାକୁ ଆପଣଙ୍କର ମାଟି ବିବରଣୀ ମାନୁଆଲ ଭାବରେ ପ୍ରବେଶ କରନ୍ତୁ |",
        soilAnalysisInput: "ମୃତ୍ତିକା ବିଶ୍ଳେଷଣ ଇନପୁଟ୍",
        selectFarm: "ଏକ ଫାର୍ମ ବାଛନ୍ତୁ (ବૈકલ્પିକ)",
        selectFarmPlaceholder: "ସ୍ବୟଂ-ପୁରଣ ତଥ୍ୟ ପାଇଁ ଏକ ଫାର୍ମ ବାଛନ୍ତୁ...",
        farmDataLoaded: "✓ ଫାର୍ମ ତଥ୍ୟ ସ୍ୱୟଂଚାଳିତ ଭାବରେ ଲୋଡ୍ ହୋଇଛି | ଆବଶ୍ୟକ ହେଲେ ଆପଣ ନିମ୍ନରେ ମୂଲ୍ୟଗୁଡ଼ିକୁ ପରିବର୍ତ୍ତନ କରିପାରିବେ |",
        nitrogen: "ନାଇଟ୍ରୋଜେନ୍ (N) ସ୍ତର",
        phosphorus: "ଫସଫରସ୍ (P) ସ୍ତର",
        potassium: "ପୋଟାସିୟମ୍ (K) ସ୍ତର",
        ph: "ମାଟିର pH ସ୍ତର",
        unit: "(mg/kg)",
        phUnit: "(0-14 ସ୍କେଲ୍)",
        placeholder_e_g: "ଯେପରି,",
        recommendCrop: "ଫସଲ ସୁପାରିଶ କରନ୍ତୁ",
        analyzing: "ମାଟି ବିଶ୍ଳେଷଣ କରୁଛି...",
        recommendedCropTitle: "ସୁପାରିଶ କରାଯାଇଥିବା ଫସଲ",
        suitability: "ଉପଯୁକ୍ତତା",
        excellentMatch: "ଉତ୍କୃଷ୍ଟ ମେଳ",
        veryGoodMatch: "ବହୁତ ଭଲ ମେଳ",
        goodMatch: "ଭଲ ମେଳ",
        fairMatch: "ଠିକ୍ ମେଳ",
        nextSteps: "ପରବର୍ତ୍ତୀ ପଦକ୍ଷେପ",
        nextStepsText: "ରୋପଣ ପୂର୍ବରୁ ସ୍ଥାନୀୟ କୃଷି ବିଶେଷଜ୍ଞଙ୍କ ସହିତ ପରାମର୍ଶ କରିବା ଏବଂ ବଜାର ସ୍ଥିତି ଯାଞ୍ଚ କରିବାକୁ ବିଚାର କରନ୍ତୁ | ଏହି ସୁପାରିଶଗୁଡ଼ିକୁ ବୈଧ କରିବାକୁ ଆପଣ ପ୍ରଥମେ ଏକ ଛୋଟ ଅଞ୍ଚଳ ପରୀକ୍ଷା କରିବାକୁ ମଧ୍ୟ ଚାହିଁପାରନ୍ତି |",
        fillAllFields: "ଦୟାକରି ସମସ୍ତ ମୃତ୍ତିକା ପାରାମିଟର ଫିଲ୍ଡଗୁଡିକ ପୁରଣ କରନ୍ତୁ |",
    },
    pestIdentifier: {
        pageTitle: "କୀଟ ଏବଂ ରୋଗ ଚିହ୍ନଟ କରନ୍ତୁ",
        pageSubtitle: "ଏକ ତତକ୍ଷଣାତ୍ AI- ଚାଳିତ ବିଶ୍ଳେଷଣ ଏବଂ ଚିକିତ୍ସା ସୁପାରିଶ ପାଇବାକୁ ପ୍ରଭାବିତ ଉଦ୍ଭିଦ ପତ୍ର କିମ୍ବା କୀଟର ଏକ ସ୍ପଷ୍ଟ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ |",
        uploadTitle: "ଉଦ୍ଭିଦ ଛବି ଅପଲୋଡ୍ କରନ୍ତୁ |",
        dropPrompt: "ଏଠାରେ ଛବି ଛାଡନ୍ତୁ |",
        uploadPrompt: "ଆପଣଙ୍କର ଛବି ଏଠାରେ ଟାଣନ୍ତୁ ଏବଂ ଛାଡନ୍ତୁ, କିମ୍ବା ଫାଇଲ୍ ବ୍ରାଉଜ୍ କରିବାକୁ କ୍ଲିକ୍ କରନ୍ତୁ |",
        clickToUpload: "ଫଟୋ ଅପଲୋଡ୍ କରିବାକୁ କ୍ଲିକ୍ କରନ୍ତୁ |",
        fileSupport: "10MB ପର୍ଯ୍ୟନ୍ତ JPG, PNG, WebP ଫାଇଲଗୁଡ଼ିକୁ ସମର୍ଥନ କରେ |",
        imagePreview: "ଛବି ପୂର୍ବାବଲୋକନ",
        analyze: "ଛବି ବିଶ୍ଳେଷଣ କରନ୍ତୁ |",
        analyzing: "ଛବି ବିଶ୍ଳେଷଣ କରୁଛି...",
        analysisResult: "ବିଶ୍ଳେଷଣ ଫଳାଫଳ",
        symptoms: "ସାଧାରଣ ଲକ୍ଷଣ",
        recommendedActions: "ସୁପାରିଶ କରାଯାଇଥିବା କାର୍ଯ୍ୟଗୁଡ଼ିକ |",
        organicSolutions: "ଜୈବିକ ସମାଧାନ",
        preventionTips: "ପ୍ରତିରୋଧ ଟିପ୍ସ",
        getTreatmentGuide: "ବିସ୍ତୃତ ଚିକିତ୍ସା ଗାଇଡ୍ ପାଆନ୍ତୁ |",
        findSuppliers: "ସ୍ଥାନୀୟ ଯୋଗାଣକାରୀଙ୍କୁ ଖୋଜନ୍ତୁ |",
        analyzeAnother: "ଅନ୍ୟ ଏକ ଛବି ବିଶ୍ଳେଷଣ କରନ୍ତୁ |",
        alert_selectImage: "ଦୟାକରି ପ୍ରଥମେ ଏକ ଛବି ବାଛନ୍ତୁ |",
        alert_invalidFile: "ଦୟାକରି ଏକ ବୈଧ ଛବି ଫାଇଲ୍ (JPG, PNG, ଇତ୍ୟାଦି) ବାଛନ୍ତୁ |",
    }
  }
};


const LanguageContext = React.createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = React.useState('en');
  const value = { language, setLanguage, T: translations[language] };
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
    const context = React.useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
